version: '3.1'

services:
   
  wordpress:
    image: wordpress
    container_name: wordpress
    restart: always
    ports:
       - 80:80
       - 443:443
    environment:
       WORDPRESS_DB_HOST: db
       WORDPRESS_DB_USER: admin
       WORDPRESS_DB_PASSWORD: password
       WORDPRESS_DB_NAME: wordpress
    volumes:
       - ./www:/var/www/html
 
  db:
    image: linuxserver/mariadb
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./db:/config
    ports:
      - 3306:3306

  phpmyadmin:
    image: ebspace/armhf-phpmyadmin
    links:
            - db:db
    environment:
       PMA_HOST: db
       PMA_PORT: 3306
       PMA_USER: admin
       PMA_PASSWORD: password
    ports:
      - 8888:80
      - 8843:443

volumes:
  wordpress:
  db:
